name: Update Kino Data
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Fetch and Save
        run: |
          python -c "
          import requests, pandas as pd
          headers = {'User-Agent': 'Mozilla/5.0'}
          try:
              res = requests.get('https://api.opap.gr/draws/v3.0/1100/last/100', headers=headers).json()
              draws = [d['winningNumbers']['list'] for d in res]
              pd.DataFrame(draws).to_csv('kino_data.csv', index=False)
          except Exception as e:
              print(e); exit(1)
          "
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add kino_data.csv
          git commit -m "Auto update data" || exit 0
          git push
